<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">

    <title>Страница не найдена!</title>

    <!-- bootstrap core css -->
    <link href="/app/css/bootstrap.min.css" rel="stylesheet">

</head>
<body>
  
   <div class="container">
      <div style="margin-top: 30px;">
          <div class="row">
            <div class="col-md-12">
              <h1 style="font-size: 5em;">404 Страница не найдена!</h1>
              <small>Опаа! что то пошло не так ((</small>
                <?php view_path(__FILE__); ?>
               <a href="/">На главную</a>
             </div>
            </div>
      </div>
   </div>

   <!-- scripts -->
</body>
</html>